Updated pull() function.

diff --git a/zsh/zshrc.d/zfunc b/zsh/zshrc.d/zfunc
--- a/zsh/zshrc.d/zfunc
+++ b/zsh/zshrc.d/zfunc
@@ -130,64 +130,72 @@ aklab() {
         curl -I ${AKFLAGS[@]} "$*"
 }
 
+
+# pull() function iterates through each Git repository under the specified root directory and pulls changes.
+#
+# Directory Structure:
+#   The function assumes a specific directory structure where Git repositories are organized under a root directory.
+#   Each Git repository should have a .git directory at its root.
+#
+# Usage:
+#   Call the pull() function without any arguments to pull changes from all Git repositories under the default root directory.
+#   Optionally, specify a root directory as an argument to pull changes from repositories under that directory.
+#
+# Functionality:
+#   - Loops through each directory containing a .git directory under the specified root directory.
+#   - Extracts project and repository names from the directory path.
+#   - Determines the Git service icon (Bitbucket, GitLab, GitHub) based on the directory path.
+#   - Changes directory to the parent directory of the Git repository.
+#   - Checks if the directory is a valid Git repository by verifying the presence of a .git directory.
+#   - Pulls changes from the Git repository.
+#   - Calculates padding for displaying project and repository names neatly.
+#   - Outputs the project and repository names, Git service icon, and pull status.
+#   - Continues to the next repository if any error occurs during the process.
+#
+# Example:
+#   To pull changes from all Git repositories on a specific git server (github for example):
+#       pull github.com
+#
+#   To pull changes from all Git repositories under the default root directory:
+#       pull
+#   
+#   To pull changes from repositories under a specific root directory (github user):
+#       pull github.com/username
+#
+# Note:
+#   Ensure that the root directory contains valid Git repositories with a .git directory at their root.
+#   Make sure to run this function from a shell environment with Git installed and configured.
 pull() {
     # Set the root directory for Git repositories
     local git_root="${HOME}/Projects/src/$*"
 
-    # Set the alias for ls based on the OS
-    if [[ $OSTYPE == 'linux-gnu' ]]; then
-        local ls_alias="ls --color=never"
-    else
-        local ls_alias="ls"
-    fi
-
     # Loop through each Git repository and pull changes
-    while read -r url; do
-        local project=""
-        local repo=""
+    while IFS= read -r git_dir; do
+        local parent_dir="$(dirname "$git_dir")"
+        local grandparent_dir="$(dirname "$parent_dir")"
+
+        # Extract project and repository names
+        local project=$(basename "$grandparent_dir")
+        local repo=$(basename "$parent_dir")
         local icon=""
 
-        # Determine the project and repository names based on the Git URL
-        if [[  ${url} =~ "bitbucket.org" ]]; then
-            icon=" "
+        # Determine the icon based on the URL
+        case $git_dir in
+            */bitbucket.org/*) icon=" ";;
+            */gitlab.nm.cbc.ca/*) icon=" ";;
+            */github.com/*) icon=" ";;
+        esac
 
-            if [[ "${url}" == *"https"* ]]; then
-                project=$(echo "${url}" | awk -F/ '{print $4}')
-                repo=$(echo "${url}" | awk -F/ '{print $5}' | sed 's/.git//')
-            elif [[ "${url}" == *"git@"* ]]; then
-                project=$(echo "${url}" | awk -F: '{print $2}' | awk -F/ '{print $1}')
-                repo=$(echo "${url}" | awk -F: '{print $2}' | awk -F/ '{print $2}' | sed 's/.git//')
-            fi
-
-        elif [[  ${url} =~ "gitlab.nm.cbc.ca" ]]; then
-            icon=" "
-            git_root="${HOME}/Projects/src/gitlab.nm.cbc.ca"
-
-            if [[ "${url}" == *"https"* ]]; then
-                project=$(echo "${url}" | awk -F/ '{print $4}')
-                repo=$(echo "${url}" | awk -F/ '{print $5}' | sed 's/.git//')
-            elif [[ "${url}" == *"git@"* ]]; then
-                project=$(echo "${url}" | awk -F: '{print $2}' | awk -F/ '{print $1}')
-                repo=$(echo "${url}" | awk -F: '{print $2}' | awk -F/ '{print $2}' | sed 's/.git//')
-            fi
-
-        elif [[ ${url} =~ "github.com" ]]; then
-            icon=" "
-            git_root="${HOME}/Projects/src/github.com"
-            project=$(echo "${url}" | awk -F/ '{print $4}')
-            repo=$(echo "${url}" | awk -F/ '{print $5}' | sed 's/.git//')
-        fi
-
-        # Change to the Git repository directory and pull changes
-        cd "${git_root}"/"${project}"/"${repo}"
+        # Change to the parent directory of the Git repository directory
+        cd "$parent_dir" || continue
         if [[ ! -d .git ]]; then
-            printf "%sError: %s/%s/%s is not a Git repository%s\n" ${red} ${git_root} ${project} ${repo} ${reset}
+            printf "%sError: %s is not a Git repository%s\n" "${red}" "${parent_dir}" "${reset}"
+            cd "$git_root" || return
             continue
         fi
 
         local branch=""
         local url=""
-        print $url
         branch=$(git rev-parse --abbrev-ref HEAD)
         url=$(git config --get remote.origin.url)
 
@@ -198,7 +206,7 @@ pull() {
         local max_repo_length=${#repo}
 
         # Output the project and repository names with padding
-        printf "%s %s %s %s/%s %s" ${cyan} ${icon} ${green} ${project} ${repo} ${reset}
+        printf "%s %s %s %s/%s %s" "${cyan}" "${icon}" "${green}" "${project}" "${repo}" "${reset}"
 
         # Calculate the number of spaces needed to pad the project and repo names
         local project_padding=$((max_project_length - ${#project}))
@@ -216,13 +224,13 @@ pull() {
         fi
 
         # Output the separator and Git status icon
-        printf ' %s──────•%s    %s %s \r%s\n' ${cyan} ${green} ${output} ${reset}
+        printf ' %s──────•%s    %s %s \r%s\n' "${cyan}" "${green}" "${output}" "${reset}"
 
-        cd "${git_root}"
-    done < <(find "${git_root}" -path "*/.git/config" -exec grep url {} \; | sed 's/url\ =\ //')
-
-    cd "${git_root}"
+        cd "$git_root" || return
+    done < <(find "${git_root}" -type d -name ".git")
 }
+
+
 
 #--------------------------------------------------------------#
 # A simple calculator for a simple person.
